export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_FOODTYPES = 'receive_foodtypes'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_USER = 'receive_user'
export const RESET_USER = 'reset_user'
export const RECEIVE_GOODS = 'receive_goods' // 接收商品数组
export const RECEIVE_RATINGS = 'receive_ratings' // 接收商家评价数组
export const RECEIVE_INFO = 'receive_info' // 接收商家信息
export const INCREMENT_FOOD_COUNT = 'increment_food_count' // 增加食物购买数量
export const DECREMENT_FOOD_COUNT = 'decrement_food_count' // 减少食物购买数量
export const EMPTY_CART = 'empty_cart' // 减少食物购买数量
export const RECEIVE_SEARCH_SHOP = 'receive_search_shop' // 搜索的商家
